name: Feature Request
description: Suggest a new feature or enhancement for the Drift Language project
title: "[Feature] "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the details below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see added.
      placeholder: Describe the feature you would like to see implemented...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Use Case
      description: Explain why this feature would be useful and what problem it solves.
      placeholder: Describe the problem this feature would solve or the use case it would enable...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on how this feature could be implemented, please describe them.
      placeholder: Describe your proposed solution or approach...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples that would help explain your feature request.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Contribution Guidelines
      description: By submitting this feature request, you agree to follow our contribution guidelines.
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I understand this feature request may be subject to discussion and modification
          required: true